apiVersion: v1
kind: Service
metadata:
  name: trabalho-devops
  namespace: trabalho
spec:
  selector:
    app: trabalho-devops
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: trabalho-devops
    protocol: TCP
    port: 8000 
    targetPort: 8000 
  