apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trabalho-devops.fullname" . }}

  labels:
    {{- include "trabalho-devops.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "trabalho-devops.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "trabalho-devops.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{.Values.resources.requests.memory}}
          limits:
            cpu: {{.Values.resources.limits.cpu}}
            memory: {{.Values.resources.limits.memory}}
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: {{ include "trabalho-devops.fullname" . }}
              key: PORT
          
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
