# trabalho-devops/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trabalho-devops.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
spec:
  selector:
    app: {{ include "trabalho-devops.name" . }}
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinityConfig.clientIP.timeoutSeconds }}
  ports:
    - name: {{ .Values.service.ports.name }}
      protocol: {{ .Values.service.ports.protocol }}
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}

